version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

jobs:
  post_create_environment:
    - pip install poetry==1.8.2
  post_install:
    - poetry install --with docs --no-interaction
