version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py  # Path to your Sphinx conf.py file

python:
  install:
    - method: pip
      path: .  # This installs your package from the current directory
      extra_requirements:
        - docs  # This installs the optional 'docs' dependencies from pyproject.toml
